language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
  
env:
  - APScheduler==3.3.1
  - Flask==0.12
  - mysqlclient==1.3.10
  - pycrypto==2.6.1
  - requests==2.13.0
  - selenium==3.0.2
      
# command to install dependencies
# add "- pip install -q Flask==$FLASK" to install below to run the tests on several version of Flask
install: 
  - pip install -r requirements.txt
  
# command to run tests
script: pytest

# send to coveralls
after_success:
    - coveralls
